[theme]
primaryColor = "#4F55F1"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0D0D0D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
